### ISSUE TITLE
Support Winston v3

### ISSUE THREAD

**Issue by jshado1** [namshi/newrelic-winston#4]
This transport triggers deprecation warnings from Winston.

I wrote an updated version that I can contribute, but is this repo dead? It looks like it hasn't been updated in 3+ years. If it is dead, I'll publish it separately.

**Comment by odino** [comment]
Hi @jshado1, thanks for bringing this up! We no longer use the nr-winston logger for a number of reasons, but are happy to review PRs to fix / upgrade functionalities :)

If you have a few things you'd actively want to implement in the library we could add you to the list of contributors to ease the process :)

Cheers!

**Comment by jshado1** [comment]
@odino What are your reasons for no-longer using nr-winston? I'm wondering if there's something I haven't considered.

Sure, I'll send over a PR. I need to update the specs first.

**Comment by odino** [comment]
Nothing crazy tbh, just that in a lot of apps we currently simply log to stdout through the console or [lib-logger](https://github.com/namshi/lib-logger), and new relic catches things such as `console.error(...)` which is enough most times :)

So using winston sometimes is simply overkill from what we noticed, and now have more projects not using it...

**Comment by jshado1** [comment]
@odino O.o I have not seen New Relic catching `console.error`. Did you have to do something special to get the agent to do that?

**Comment by odino** [comment]
Oh, now I remember -- we simply use [newrelic-plus](https://github.com/namshi/node-newrelic-plus/blob/master/index.js) :-P

**Comment by jshado1** [comment]
Ahh, a decorator. Interesting 🤔

**Comment by cybuhh** [comment]
What do you think about this one https://github.com/namshi/newrelic-winston/pull/5

**Comment by cybuhh** [comment]
small bufix/update https://github.com/namshi/newrelic-winston/pull/6

**Comment by jshado1** [comment]
@odino, I think this was resolved @cybuhh and can be closed?

**Comment by odino** [comment]
:+1:
